version: '3.7'
services:
  service1:
    image: kishanvekaria/service1
    build: ./service1
    environment: 
      DB_URI: ${DB_URI}
      SEC_KEY: ${SEC_KEY}
    deploy:
      replicas: 2
    ports:
    - target: 5000
      protocol: tcp

  service2:
    image: kishanvekaria/service2
    build: ./service2
    deploy:
      replicas: 2
    ports:
    - target: 5001
      protocol: tcp

  service3:
    image: kishanvekaria/service3
    build: ./service3
    deploy:
      replicas: 2
    ports:
    - target: 5002
      protocol: tcp

  service4:
    image: kishanvekaria/service4
    build: ./service4
    deploy:
      replicas: 2
    ports:
    - target: 5003
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
