version: '3.7'
services:
  service1:
    container_name: service1
    build: ./service1
    ports:
    - target: 5000
      protocol: tcp
    depends_on: 
    - service2 
    - service3 
    - service4

  service2:
    container_name: service2
    build: ./service2
    ports:
    - target: 5001
      protocol: tcp

  service3:
    container_name: service3
    build: ./service3
    ports:
    - target: 5002
      protocol: tcp

  service4:
    container_name: service4
    build: ./service4
    ports:
    - target: 5003
      protocol: tcp
    depends_on: 
    - service2
    - service3

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - service1 